cart/urls.py
'''from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('cart/', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
]'''


from django.urls import path
from .views import ViewCartView, AddToCartView, RemoveFromCartView

app_name = 'cart'

urlpatterns = [
    path('cart/', ViewCartView.as_view(), name='view_cart'),
    path('add/<int:product_id>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove/<int:item_id>/', RemoveFromCartView.as_view(), name='remove_from_cart'),
]

deliver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from cake_api import views
from customer.views import Index, About, Order, OrderConfirmation, OrderPayConfirmation, Menu, MenuSearch, MenuDetail

app_name = 'deliver'

router = routers.DefaultRouter()
router.register(r'orders', views.OrderModelViewSet, basename='orders')
router.register(r'orderitem', views.OrderItemViewSet, basename='orderitem')
router.register(r'customerdata', views.CustomerDataViewSet, basename='customerdata')
router.register(r'deliverdata', views.DeliverDataViewSet, basename='deliverdata')

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('', include('cart.urls', namespace='cart')),
    path('', Index.as_view(), name='index'),
    path('about/', About.as_view(), name='about'),
    path('menu/', Menu.as_view(), name='menu'),
    path('menu/search/', MenuSearch.as_view(), name='menu-search'),
    path('menu-detail/<int:id>/', MenuDetail.as_view(), name='menu-detail'),
    path('order/', Order.as_view(), name='order'),
    path('order-confirmation/<int:pk>', OrderConfirmation.as_view(),
         name='order-confirmation'),
    path('payment-confirmation/', OrderPayConfirmation.as_view(),
         name='payment-confirmation'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from datetime import date
from django.utils import timezone


class MenuItem(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='menu_images/')
    price = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.ManyToManyField('Category', related_name='item')

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class OrderModel(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    items = models.ManyToManyField(MenuItem, related_name='order', blank=True)
    is_paid = models.BooleanField(default=False)
    is_shipped = models.BooleanField(default=False)

    def __str__(self):
        return f'Order: {self.items}'


class CustomerData(models.Model):
    order = models.ForeignKey(OrderModel, on_delete=models.CASCADE)
    deliver_date = models.DateField(default=date.today, blank=True, null=True)
    deliver_time = models.TimeField(default=timezone.now, blank=True, null=True)
    cake_text = models.TextField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    street = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=15, blank=True, null=True)
    zip_code = models.IntegerField(blank=True, null=True)
    phone = models.IntegerField(blank=False, null=True)

    def __str__(self):
        return f'{self.order} - {self.name}'


class DeliverData(models.Model):
    order = models.ForeignKey(OrderModel, on_delete=models.CASCADE)
    deliver_name = models.CharField(max_length=50, blank=True, null=True)
    deliver_email = models.CharField(max_length=50, blank=True, null=True)
    deliver_street = models.CharField(max_length=50, blank=True, null=True)
    deliver_city = models.CharField(max_length=50, blank=True, null=True)
    deliver_state = models.CharField(max_length=15, blank=True, null=True)
    deliver_zip_code = models.IntegerField(blank=True, null=True)
    deliver_phone = models.IntegerField(blank=False, null=True)

    def __str__(self):
        return f'{self.order} - {self.name}'


class Cart(models.Model):
    product = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quantity} x {self.product.name}'

    def total_price_item(self):
        return self.product.price * self.quantity


class OrderItem(models.Model):
    order = models.ForeignKey(OrderModel, on_delete=models.CASCADE)
    name = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return f'{self.order} - {self.name} x {self.quantity}'

    def print_details(self):
        print(f"Order: {self.order}")
        print(f"Item: {self.name.name}")
        print(f"Quantity: {self.quantity}")

customer/views.py
import json
from django.shortcuts import render, redirect, HttpResponse
from django.views import View
from django.db.models import Q
from django.core.mail import send_mail
from .models import MenuItem, Category, OrderModel, Cart, OrderItem, CustomerData, DeliverData
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from cart.forms import InputQuantity
from django.contrib import messages
from datetime import date


class Index(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'customer/index.html')

    def test_func(self):
        return self.request.user.groups.filter(name='Staff').exists()


class About(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'customer/about.html')

    def test_func(self):
        return self.request.user.groups.filter(name='Staff').exists()


class Order(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        items = Cart.objects.all()
        context = {
            'items': items,
        }
        return render(request, 'customer/order.html', context)

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        email = request.POST.get('email')
        street = request.POST.get('street')
        city = request.POST.get('city')
        state = request.POST.get('state')
        zip_code = request.POST.get('zip')
        phone = request.POST.get('phone')
        cake_text = request.POST.get('cake_text')
        deliver_date = request.POST.get('deliver_date')
        deliver_time = request.POST.get('deliver_time')
        deliver_name = request.POST.get('deliver_name')
        deliver_email = request.POST.get('deliver_email')
        deliver_street = request.POST.get('deliver_street')
        deliver_city = request.POST.get('deliver_city')
        deliver_state = request.POST.get('deliver_state')
        deliver_zip_code = request.POST.get('deliver_zip')
        deliver_phone = request.POST.get('deliver_phone')

        order_items = {
            'items': []
        }

        cart_items = Cart.objects.all()
        items = [item.product_id for item in cart_items]

        for item in items:
            menu_item = MenuItem.objects.get(pk__contains=item)
            quant = Cart.objects.get(product_id=item)

            item_data = {
                'id': menu_item.pk,
                'name': menu_item.name,
                'price': menu_item.price,
                'quantity': quant.quantity,
            }

            order_items['items'].append(item_data)

            price = 0
            item_ids = []

        for item in order_items['items']:
            price += item['price']*item['quantity']
            item_ids.append(item['id'])

        order = OrderModel.objects.create(
            price=price
        )
        order.items.add(*item_ids)

        if not deliver_date:
            deliver_date = date.today()

        customer = CustomerData.objects.create(
            order=order,
            name=name if name else None,
            email=email if email else None,
            street=street if street else None,
            city=city if city else None,
            state=state if state else None,
            zip_code=zip_code if zip_code else None,
            phone=phone if phone else None,
            deliver_date=deliver_date,
            deliver_time=deliver_time if deliver_time else None,
            cake_text=cake_text if cake_text else None,
        )

        if not deliver_name:
            deliver_name = name
        if not deliver_email:
            deliver_email = email
        if not deliver_street:
            deliver_street = street
        if not deliver_city:
            deliver_city = city
        if not deliver_state:
            deliver_state = state
        if not deliver_zip_code:
            deliver_zip_code = zip_code
        if not deliver_phone:
            deliver_phone = phone

        deliver = DeliverData.objects.create(
            order=order,
            deliver_name=deliver_name,
            deliver_email=deliver_email,
            deliver_street=deliver_street,
            deliver_city=deliver_city,
            deliver_state=deliver_state,
            deliver_zip_code=deliver_zip_code,
            deliver_phone=deliver_phone,
        )
        for cart_item in cart_items:
            OrderItem.objects.create(order=order, name=cart_item.product, quantity=cart_item.quantity)

        # After everything is done, send confirmation email to the user
        body = ('Thank you for your order! Your food is being made and will be delivered soon!\n'
                f'Your total: {price}\n'
                'Thank you again for your order!')

        send_mail(
            'Thank You For Your Order!',
            body,
            'example@example.com',
            [email],
            fail_silently=False
        )

        Cart.objects.all().delete()

        return redirect('order-confirmation', pk=order.pk)

    def test_func(self):
        return self.request.user.groups.filter(name='Staff').exists()


class OrderConfirmation(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, pk, *args, **kwargs):
        order = OrderModel.objects.get(pk=pk)

        context = {
            'pk': order.pk,
            'items': order.items,
            'price': order.price,
        }

        return render(request, 'customer/order_confirmation.html', context)

    def post(self, request, pk, *args, **kwargs):
        data = json.loads(request.body)

        if data['isPaid']:
            order = OrderModel.objects.get(pk=pk)
            order.is_paid = True
            order.save()

        return redirect('payment-confirmation')

    def test_func(self):
        return self.request.user.groups.filter(name='Staff').exists()


class OrderPayConfirmation(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'customer/order_pay_confirmation.html')

    def test_func(self):
        return self.request.user.groups.filter(name='Staff').exists()


class Menu(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        menu_items = MenuItem.objects.all()

        context = {
            'menu_items': menu_items
        }

        return render(request, 'customer/menu.html', context)

    def test_func(self):
        return self.request.user.groups.filter(name='Staff').exists()


class MenuSearch(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get("q")

        menu_items = MenuItem.objects.filter(
            Q(name__icontains=query) |
            Q(price__icontains=query) |
            Q(description__icontains=query)
        )

        context = {
            'menu_items': menu_items
        }

        return render(request, 'customer/menu.html', context)

    def test_func(self):
        return self.request.user.groups.filter(name='Staff').exists()


class MenuDetail(LoginRequiredMixin, UserPassesTestMixin, View):

    def get(self, request, id, *args, **kwargs):
        product = MenuItem.objects.get(id=id)
        if request.method == 'POST':
            form = InputQuantity(request.POST)
            if form.is_valid():
                cantitate = form.cleaned_data.get('cantitate')
                return HttpResponse("Form value received: " + cantitate)
        else:
            form = InputQuantity
        context = {
            'product': product,
            'form': form,
        }
        return render(request, 'customer/menu_detail.html', context)

    def test_func(self):
        return self.request.user.groups.filter(name='Staff').exists()

customer/templates/customer/about.html
{% extends 'customer/base.html' %}

{% block content %}
<div class="container mb-5">
    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12 offset-md-1 p-4 text-center">
            <h1>Despre noi!</h1>
        </div>
    </div>
    <div class="row justify-content-center mt-1">
        <div class="col-md-10 col-sm-12 offset-md-1 p-4 text-center">
            <p>La finele anului 2009, Cake Expert a luat naștere în Iași, cu un prim laborator și micul magazin de pe Bulevardul Chimiei, nr 35. Alături de oamenii Cake Expert am creat povești dulci, am livrat la domiciliu zâmbete și am sărbătorit alături de clienții și colegii noștri deopotrivă. Cu timpul ne-am extins, astfel că acum ne bucurăm de 5 magazine fizice și un laborator pe Calea Chisinaului, nr 29. În fiecare zi punem muncă și pasiune în produsele noastre astfel încât fiecare mușcătură dintr-un tort cu ciocolată, un tort cu fructe sau un tort medovik să îți gâdile papilele și să-ți creeze cele mai frumoase amintiri.</p>
        </div>
    </div>
</div>
{% endblock content %}

customer/templates/customer/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", inital-scale=1.0, shrink-to-fit=no">
    <title>Cake Expert</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script-->

</head>
<body>
    {% include 'customer/navigation.html' %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        {% endif %}
    {% block content %}
    {% endblock content %}
    {% include 'customer/footer.html' %}

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
</body>
</html>

customer/templates/customer/footer.html
<footer class="page-footer-light font-medium fixed-bottom" style="background-color:#ff96fa;">
    <div class="footer-copyright text-center py-3" style="color:#ffffff">&copy; 2024 Copyright:
        <a href="{% url 'index' %}" style="color:#ffffff">Acasa</a>
        <a class="ml-3" href="{% url 'dashboard' %}" style="color:#ffffff"> Staff Login</a>
        <a class="ml-3" href="{% url 'account_logout' %}" style="color:#ffffff"> Logout</a>
    </div>
</footer>

customer/templates/customer/index.html
{% extends 'customer/base.html' %}

{% block content %}
<div class="container mb-5">
    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12 offset-md-1 p-4 text-center">
            <h1>Pagina de comenzi online - Cake Expert</h1>
        </div>
    </div>
    <div class="row justify-content-center mt-1">
        <div class="card col-md-5 col-sm-12 offset-md-1 p-4 text-center">
            <h2>Plasati o comanda!</h2>
            <a href="{% url 'menu' %}" class="btn btn-outline-pink">Plasati o comanda!</a>
        </div>
    </div>
</div>
{% endblock content %}

customer/templates/customer/menu.html
{% extends 'customer/base.html' %}

{% block content %}
<div class="container" style="padding-top:30px; padding-bottom:40px">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 col-sm-12 text-center">
            <h1>Produsele noastre</h1>
        </div>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12 text-center">
            <form method="GET" action="{% url 'menu-search' %}">
                <div class="md-form mt-0 active-cyan-2">
                    <input class="form-control" name="q" type="text" placeholder="Cautati in produse" aria-label="Search" value="{{ request.GET.q }}">
                </div>
            </form>
        </div>
    </div>

    <div class="row justify-content-center">
        {% for item in menu_items %}
        <div class="col-md-4 col-sm-12 text-center mb-5">
            <img class="rounded" src="{{ item.image.url }}" width="350" height="300">
            <h5 class="mt-3">{{ item.name }}</h5>
            <p>Pret: {{ item.price }} lei/kg</p>
            <a href="{% url 'menu-detail' item.id %}">
                <input type="submit" value="Detalii" class="btn btn-secondary btn-sm" type="button"/>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

customer/templates/customer/menu_detail.html
{% extends 'customer/base.html' %}

{% block content %}
<style>
    /* Style the "Buy Now" button */
    .buy-now-button {
        display: block;
        margin-top: 10px;
        margin-right: 45px;
        background-color:#ff96fa;
        color: #fff;
        text-decoration: none;
        padding: 5px 10px;
        border-radius: 5px;
    }
</style>
<div class = "container" style="padding-top: 30px">
    <br><br>
    <div class="row">
        <div class="col-md-5">
          <br>
          <img class="rounded" src="{{ product.image.url }}" width="450" height="400">
          <br><br>
          <h3 class="card-title text-center ">{{ product.name }}</h3>
          <h5 class="card-title text-center ">Pret  {{ product.price }} lei/kg</h5>
        </div>
        <div class="col-md-7 shadow-lg p-3 mb-5 bg-white rounded">
          <h1 class="my-3">Descriere</h1>
          <p class = "lead">{{ product.description }}</p>
        <br/>
            <br/>
                <div class="row justify-content-center">
                <form action="{% url 'cart:add_to_cart' product.id %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Adauga la comanda">
                </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

customer/templates/customer/navigation.html
{% load cart_tags %}

<nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color:#ff96fa;">
  <a class="navbar-brand" href="{% url 'index' %}">Acasa</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">Despre noi</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" href="{% url 'menu' %}">Produse</a>
      </li>
    </ul>
          <!-- Cart icon with item count -->
    <a href="{% url 'cart:view_cart' %}" class="nav-item nav-link">
        <i class="fa fa-shopping-cart"></i> Comanda
        {% cart_item_count as cart_count %}
        {% if cart_count %}
            <span class="badge badge-pill" style="background-color: black;">{{ cart_count }}</span>
        {% endif %}
    </a>
  </div>
</nav>
<style>
    .navbar-brand, .nav-item.nav-link {
        color: black; /* Change the color of navbar brand and links to black */
    }
    .badge {
        background-color: black; /* Change the background color of the badge to black */
        color: white; /* Change the text color of the badge to white */
    }
</style>

customer/templates/customer/order_confirmation.html
{% extends 'customer/base.html' %}

{% block content %}
<div class="container mb-5" style="padding-top:50px">
    <div class="row justify-content-center mt-1">
        <div class="col-md-5 col-sm-12 p-4 text-center">
            <h1>Comanda transmisa!</h1>
            <p>In curand veti primi un email de confirmare a comenzii.</p>
            <a href="{% url 'index' %}">Mergi la pagina principala</a>
        </div>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="col-md-5 col-sm-12 text-center">
            <h3 class="pb-3">Sumarul comenzii:</h3>
            {% for item in items.all %}
                <p>{{ item.name }}: <span class="pl-3">{{ item.price }} lei/kg ({{ item.item_quantity }})</span></p>
            {% endfor %}

            <p class="font-weight-bold pt-4">Total: {{ price }} lei</p>
        </div>
    </div>
    <div class="row justify-content-center pb-2 pt-5">
        <div class="col-md-6 text-center">
            <h3>Platiti acum sau numerar la livrare</h3>
        </div>
    </div>
    <div class="row justify-content-center pb-5">
        <div class="col-md-6 text-center">
            <div id="paypal-button"></div>
        </div>
    </div>
</div>

<script src="https://www.paypalobjects.com/api/checkout.js"></script>
<script>
  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
const csrftoken = getCookie('csrftoken');

  paypal.Button.render({
    // Configure environment
    env: 'sandbox',
    client: {
      sandbox: 'ATf0mGB3vK4K0ruj9oujCFC_YSC_2W-PmNuNYNdcqdixOKmz7mic_Wadms0Ua7d7X9T4sl9phxJwwgIh',
      production: 'demo_production_client_id'
    },
    // Customize button (optional)
    locale: 'en_US',
    style: {
      size: 'large',
      color: 'blue',
      shape: 'rect',
    },

    // Enable Pay Now checkout flow (optional)
    commit: true,

    // Set up a payment
    payment: function(data, actions) {
      return actions.payment.create({
        transactions: [{
          amount: {
            total: '{{ price }}',
            currency: 'USD'
          }
        }]
      });
    },
    // Execute the payment
    onAuthorize: function(data, actions) {
      return actions.payment.execute().then(function() {
        // Show a confirmation message to the buyer
        $.ajax({
            type: 'POST',
            url: "{% url 'order-confirmation' pk %}",
            beforeSend: function(request) {
                request.setRequestHeader('X-CSRFToken', csrftoken)
            },
            data: JSON.stringify({'isPaid': true}),
            success: function(data) {
                window.location.href = '/payment-confirmation/'
            }
        })
      });
    }
  }, '#paypal-button');

</script>
{% endblock content %}

customer/templates/customer/order_pay_confirmation.html
{% extends 'customer/base.html' %}

{% block content %}
<div class="container mb-5">
    <div class="row justify-content-center mt-1">
        <div class="col-md-5 col-sm-12 p-4 text-center">
            <h1>Payment Submitted!</h1>
            <a href="{% url 'index' %}">Go to the homepage</a>
        </div>
    </div>
</div>
{% endblock content %}

customer/templates/customer/platouri.html
{% extends 'customer/base.html' %}

{% block content %}
<div class="container" style="padding-top:30px">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 col-sm-12 text-center">
            <h1>Platourile noastre</h1>
        </div>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12 text-center">
            <form method="GET" action="{% url 'menu-search' %}">
                <div class="md-form mt-0 active-cyan-2">
                    <input class="form-control" name="q" type="text" placeholder="Cautati in produse" aria-label="Search" value="{{ request.GET.q }}">
                </div>
            </form>
        </div>
    </div>

    <div class="row justify-content-center">
        {% for item in items %}
        <div class="col-md-4 col-sm-12 text-center mb-5">
            <img class="rounded" src="{{ item.image.url }}" width="350" height="300">
            <h5 class="mt-3">{{ item.name }}</h5>
            <p>Pret: {{ item.price }} lei/kg</p>
            <a href="{% url 'menu-detail' item.id %}">
                <input type="submit" value="Detalii" class="btn btn-secondary btn-sm" type="button"/>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

customer/templates/customer/prajituri.html
{% extends 'customer/base.html' %}

{% block content %}
<div class="container" style="padding-top:30px">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 col-sm-12 text-center">
            <h1>Prajiturile noastre</h1>
        </div>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12 text-center">
            <form method="GET" action="{% url 'menu-search' %}">
                <div class="md-form mt-0 active-cyan-2">
                    <input class="form-control" name="q" type="text" placeholder="Cautati in produse" aria-label="Search" value="{{ request.GET.q }}">
                </div>
            </form>
        </div>
    </div>

    <div class="row justify-content-center">
        {% for item in items %}
        <div class="col-md-4 col-sm-12 text-center mb-5">
            <img class="rounded" src="{{ item.image.url }}" width="350" height="300">
            <h5 class="mt-3">{{ item.name }}</h5>
            <p>Pret: {{ item.price }} lei/kg</p>
            <a href="{% url 'menu-detail' item.id %}">
                <input type="submit" value="Detalii" class="btn btn-secondary btn-sm" type="button"/>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

customer/templates/customer/tort_detail.html
{% extends 'customer/base.html' %}

{% block content %}

<div class = "container" style="padding-top: 30px">
    <br><br>
    <div class="row">
        <div class="col-md-5">
          <br>
          <img class="rounded" src="{{ item.image.url }}" width="450" height="400">
          <br><br>
          <h3 class="card-title text-center ">{{ item.name }}</h3>
          <h5 class="card-title text-center ">Pret  {{ item.price }} lei/kg</h5>
        </div>
        <div class="col-md-7 shadow-lg p-3 mb-5 bg-white rounded">
          <h1 class="my-3">Descriere</h1>
          <p class = "lead">{{ item.description }}</p>
        </div>
    </div>
</div>

{% endblock content %}